### ISSUE TITLE
custom-domain-routes no routes found

### ISSUE THREAD

**Issue by 0anton** [SAP-samples/btp-cap-multitenant-saas#24]
Hi,

I'm following the instruction https://github.com/SAP-samples/btp-cap-multitenant-saas/blob/main/docu/4-expert/-CloudFoundry-/custom-domain-usage/README.md and get stuck in the following configuration.

I'm trying to create a custom domain mapping in my sub-account. I'm experiencing the inconsistent behaviour, which is cannot troubleshoot myself, so I kindly ask you to help me. The mapping creation finishes successfully:

d057039:my_own_rootCA$ cf custom-domain-map-route myapp-app-router.cfapps.eu12.hana.ondemand.com aaa.mydomain.cloud.sap
Command: custom-domain-map-route
Organisation:  tdo-dev  (184bdae4-0c2f-4174-9a64-fb847e13d13e)
API Endpoint:  https://api.cf.eu12.hana.ondemand.com/
Custom-Domain API Server:  https://custom-domain-certificates-api.cf.eu12.hana.ondemand.com/
OK

However the consequent mapping check shows the mapping is not created:

d057039:my_own_rootCA$ cf custom-domain-routes
Command: custom-domain-routes
Organisation:  tdo-dev  (184bdae4-0c2f-4174-9a64-fb847e13d13e)
API Endpoint:  https://api.cf.eu12.hana.ondemand.com/
Custom-Domain API Server:  https://custom-domain-certificates-api.cf.eu12.hana.ondemand.com/

No routes found

Trying to access the custom domain via web-browser confirms the mapping was not created:

https://aaa.tdo.cloud.sap/
404 Not Found: Requested route ('aaa.mydomain.cloud.sap') does not exist.

How can I create the mapping?

**Comment by alperdedeoglu** [comment]
Hi @0anton, 
Thank you very much for your interest in our sample repository.
From the domain you are using I understand that you are SAP Internal.

Custom Domain section of the repository aims guidance for SAP Partners and SAP Customers only. (May be we should mention that in the documentation since the repository gets also attraction from internal colleagues.)

I will share with you the internal guidence about the usage of SAP subdomains with SAP Custom Domain Service through internal channels and would be happy to support you.

**Comment by 0anton** [comment]
Thanks, Alper, for your kind help!

It worked best at last!

As I used the `custom-domain-service` application with the service plan `standard` I could closely follow your guide and create a custom domain for my app. Even the certificate was automatically provisioned using a DigiCert Authority!
