### ISSUE TITLE
Adoption of CAP Operator

### ISSUE THREAD

**Issue by alperdedeoglu** [SAP-samples/btp-cap-multitenant-saas#47]
For managing the project lifecycle, we need to consider the CAP Operator adoption. @skrishnan-sap can also support us on the journey?

**Comment by skrishnan-sap** [comment]
Yes, I can support to prepare a PR which brings in the necessary documentation and artefacts. 
I am currently in the process of understanding the application and trying to run through the steps with the Kyma based documentation. There are some issues I am facing for:
- NetworkPolicy configuration issue which will be fixed with https://github.com/SAP-samples/btp-cap-multitenant-saas/pull/45
- consumer tenant subscriptions are failing as the `mtxs` based deployment fails. The HDI deployer logs shows an error "hana as a replacement for service com-hdi-container undefined". I believe there is some configuration fix required for `SERVICE_REPLACEMENTS`.

@alperdedeoglu do you have a recommendation on who could help to troubleshoot?
